name: Update Supabase DB with Player Stats

on:
  schedule:
    - cron: '0 11 * * *'  # Runs every day at 11:00:00 UTC
  workflow_dispatch:  

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run update_stats_db as module
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: python -m src.scripts.live_stats
    
      - name: Commit and push log file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://github-actions:${GH_PAT}@github.com/${{ github.repository }}
          git pull origin main
          git add logs/stats_last_update.txt
          git commit -m "Update time log" || echo "No changes to commit"
          git push origin main